Improve CI workflow to include docs

diff --git a/.github/workflows/ci-cd-workflow.yml b/.github/workflows/ci-cd-workflow.yml
--- a/.github/workflows/ci-cd-workflow.yml
+++ b/.github/workflows/ci-cd-workflow.yml
@@ -36,15 +36,32 @@ jobs:
     - name: Conda info
       shell: bash -l {0}
       run: conda info
+    - name: Install dev dependencies
+      run: |
+        which python
+        conda install mesmer pip wheel
+        pip install .[dev]
     - name: Run format and linting tests
       shell: bash -l {0}
       # TODO: use make -B conda-environment when mesmer is available
       run: |
-          which python
-          conda install black flake8 isort
           black --exclude _version.py --check src tests setup.py
           flake8 src tests setup.py
           isort --check-only --quiet src tests setup.py
+    - name: Build docs
+      # treat warnings as errors (-W)...
+      # ...but not when being nitpicky (-n)
+      run: |
+          sphinx-build -M html docs/source docs/build -qW
+          sphinx-build -M html docs/source docs/build -Eqn -b coverage
+          if [[ -s docs/build/html/python.txt ]]
+          then
+              echo
+              echo \"Error: Documentation missing:\"
+              echo
+              cat docs/build/html/python.txt
+              exit 1
+          fi
 
   build:
     runs-on: ${{ matrix.os }}
@@ -74,10 +91,19 @@ jobs:
     - name: Conda info
       shell: bash -l {0}
       run: conda info
-    - name: Run tests
-      shell: bash -l {0}
-      # TDOO: use make -B test
+    - name: Install test dependencies
       run: |
-          which python
-          conda install pytest
-          pytest tests/test_source_file_headers.py
+        which python
+        conda install mesmer pip wheel
+        pip install .[tests,notebooks]
+    - name: Test with pytest
+      env:
+        MIN_COVERAGE: 90
+      run: |
+          pytest tests -r a --cov=mesmer-openscmrunner --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
+          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
+          then
+              echo
+              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
+              exit 1
+          fi
